# Generated by Django 4.2 on 2023-05-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update',
        ),
    ]
